### ISSUE TITLE
cpu占用真的没办法减少吗？有点吃力啊感觉。

### ISSUE THREAD

**Issue by ohsorry** [Chion82/kcptun-raw#18]
全速下载时cpu：
服务器的：
![kcptunrawsvr](https://user-images.githubusercontent.com/6219683/31361005-b40a9726-ad83-11e7-8261-7afb71206454.PNG)

客户端的：
![kcptunrawclient](https://user-images.githubusercontent.com/6219683/31361009-b8dfc884-ad83-11e7-9ef4-4b03344c91b8.PNG)

感觉有点吃力啊，cpu在1%以下有可能吗？

**Comment by ohsorry** [comment]
#3 能不轮询或者sleep一下吗？

**Comment by ohsorry** [comment]
另外用raw socket有效带宽三分之一都不到？--mode=normal时，传输速度3MB/s，有效数据才1MB/s。

**Comment by Chion82** [comment]
满载情况下这个CPU占用还是在可以容忍的程度下吧。原版的kcptun在满载的时候也有20%~30%的占用，kcptun-raw因为是libev的单线程模型、以最高的kcp更新频次来降低传输延迟，满载时会比较消耗CPU。如果有必要，以后会增加一个参数来让用户指定kcp更新频率，在传输延迟和资源占用之间做取舍。

关于带宽利用率，因为kcptun-raw没有引入FEC，满载传输时会可能有一部分延迟抖动导致的利用率降低。然而kcp不是适用于所有的情况，如果在不使用kcp的情况下传输速度能够达到3MB/s，其实是没有必要使用kcp的，内核开启BBR可能效果更佳。kcp适用于丢包更严重、导致带宽利用率严重底下的情况，比如当只有几百K的传输速度时，可以使用kcp。

**Comment by ohsorry** [comment]
客户端是20M带宽，tcp下载国内最快2M/s。服务器国外100M以上的带宽应该，udp被墙了，也没法测试udp下载速度。
按照你说的：
两边都使用tcp_bbr下载速度1M/s左右，但经常掉到几百Kb/s甚至300Kb/s；
服务器单边tcp_bbr下载速度50Kb/s以下；
两边使用kcptunraw下载速度接近1M/s，用iftop，nethogs发现两边的传输速度都有3Mb/s；

不知道怎么选了，kcptunraw到极限了吗？

**Comment by wangyu-** [comment]
>另外用raw socket有效带宽三分之一都不到

>两边使用kcptunraw下载速度接近1M/s，用iftop，nethogs发现两边的传输速度都有3Mb/s；

我自己没测过原版kcptun的流量。

但是我看网上有人说用原版kcptun也会消耗几倍的流量。带宽利用率低应该不是raw socket造成的，可能是你的kcp参数设得太激进了。

https://github.com/xtaci/kcptun/issues/91

看这个issue，回帖里还有人说观察到了8-10倍的流量。你重新调下参数。

**Comment by ohsorry** [comment]
我测试过kcptun， 不开启向前纠错，mode=normal下带宽略微比原生tcp多一点点。那几倍的流量可能是fast3产生的吧，或者计算回环流量了？

**Comment by ccsexyz** [comment]
只多一点点？这个一点点是1.5吗？

**Comment by ohsorry** [comment]
这是我那天的测试，左半部分是用kcptun，右边是原生tcp：
![kcptun-tcp](https://user-images.githubusercontent.com/6219683/31372316-bc4f56b2-adc7-11e7-9999-9c01577c5b50.PNG)

服务器是搬瓦工的，tcp经常卡的不行，所以我用kcptun走udp流量，不开多倍发包不向前纠错。
{
  "crypt": "none",
  "mode": "normal",
  "mtu": 1350,
  "sndwnd": 128,
  "rcvwnd": 128,
  "datashard": 0,
  "parityshard": 0,
  "dscp": 0,
  "nocomp": false
}

**Comment by wangyu-** [comment]
kcptun-raw观察到3倍的流量也是用的 mode=normal吗？

**Comment by wangyu-** [comment]
kcptun-raw观察到3倍的流量用的是什么参数？

**Comment by ohsorry** [comment]
--mode normal --noseq
