### ISSUE TITLE
CPU占用问题(CPU usage issue)

### ISSUE THREAD

**Issue by qq57240** [Chion82/kcptun-raw#3]
通过ps -aux命令查看进程发现程序一直占用cpu，其他程序TIME项很低，但kcptun-raw一直占用cpu时间，并且一直累积不释放。睡了一觉起来，TIME项显示为7小时+，其他程序都在几分钟左右。
通过top命令查看，程序无ss连接时也保持1.0%cpu占用，希望作者能解决这个问题，谢谢您的工作。

Checked by command "ps -aux", the TIME of other process are in low level,but kcptun-raw always in use and no idle. "7:xx" the TIME of kcptun-raw shows ,the TIME of other process only minutes when I get up.
Cheky the command "top", the CPU usage always at 1.0% without any connection else . Hope the author of this program could resolves this issue.Appreciate it.

**Comment by Chion82** [comment]
这还是在可以容忍的范围内，虽然TIME值较高但是load值还是可以接受的。因为kcp是纯算法实现而不涉及fd，所以不能使用epoll模型而需要频繁轮询update和recv，虽然可以通过降低轮训频率或使用kcp推荐的`ikcp_check()`方法降低CPU占用，但是实测出来这样会降低带宽使用率，最高速率相差了1～2Mbytes/s。
至于空闲时仍然有1%cpu占用是因为两端需要长期维持单kcp连接（mux）和packet心跳，因此空闲时仍然有频繁的轮询操作。这么做是为了可以快速建立连接、心跳保活和快速恢复。从一定程度上说，这是为了保证程序的长期运行可靠性，而这也是原版的kcptun所欠缺的（原版kcptun经常需要人为/脚本检测重启来避免卡住）。
另外一个造成高CPU占用率的原因是使用了raw socket进行packet的收发，特别在服务端当有大量流量流入/发出时，raw socket都会收到packet并在程序内（用户态）进行过滤（程序相当于一个抓包器），从而增加了cpu占用率。
目前这个程序的参数是我在权衡程序表现性能和cpu占用后做出取舍的结果，如果实在有必要的话，以后可以添加可选参数让用户来调测。

**Comment by Chion82** [comment]
调整了一下参数，在尽量避免影响性能的前提下降低了一点CPU占用

**Comment by qq57240** [comment]
可能我表达不准确。其实我指的不是CPU占用过高，客观讲这个占用率是可以接受的。主要是那个TIME项，一直累积，其他进程都会重置这个东西，我也不太懂，就是这么一大排进程，只有kcptun-raw的TIME是特别高的。

**Comment by Chion82** [comment]
刚才提到了，由于一直有轮询任务所以操作系统会一直为本进程分配运行时间片并分配CPU，因此CPU TIME一直累积；而cpu占用率不高是因为进程占用该运行时间片的频率不高（空闲时大概5～10ms一次？）。CPU TIME和cpu占用率没有必然的关系，但是如果长期保持有较低的cpu占用率（即进程一直在占用运行时间片），就会导致CPU TIME不断增加。事实上，仔细观察还是有很多的进程有类似的表现的，比如运行在用户态的Xorg由于需要一直更新桌面环境，TIME值也很高，还比如阿里云主机上的阿里云盾进程也保持较高的TIME。其他TIME较低的进程是由于长期空闲，可能会有偶尔的高cpu占用，但计算下来总的CPU使用时间不长。
Short answer is: 这个情况不需要过分担心。

**Comment by qq57240** [comment]
谢谢作者耐心解答。我现在已经用这个代替qlang的kcptun了，很不错。玩外国游戏走这个就没掉过线，之前kcptun老掉线！

**Comment by Chion82** [comment]
虽然上层协议有加密，但是如果我们的数据帧不加密的话，本程序的各层协议头都是明文的，所以还是有必要。另外客户端需要手动填入的地址并非简单的监听地址，而是用作raw socket的发包地址，虽然程序可以从网卡获取但是这样还是很繁琐。除了可以在路由器上绑定静态ip，还可以在本地创建一个虚拟接口并分配一个静态ip，开启ip_forward，然后运行客户端时使用这个静态ip即可，内核会自动forward到正确的网卡上
