### ISSUE TITLE
连接初始化问题

### ISSUE THREAD

**Issue by sdysj** [Chion82/kcptun-raw#7]
启动程序有时候初始化不了，需要再启动一次才能完成初始化，这很不方便啊，能不能改成自动重试初始化？
具体就是有时候启动程序只显示 mode enable 而不显示 kcp ready.

这个改版不错，美中不足就是不能利用CPU多核。

**Comment by Chion82** [comment]
如果kcp ready没有马上出来，稍微等几十秒试试，会自动重连的。能够复现这个问题吗？请提供一下客户端和服务端的log。

**Comment by sdysj** [comment]
程序只显示 mode enabled 之后进程就消失了，需要重新启动直到显示 kcp ready。

**Comment by Chion82** [comment]
看看stderr的输出，进程在退出之前是不是有listen error port is in use之类的？

**Comment by sdysj** [comment]
对的。
bind error: Address already in use

**Comment by Chion82** [comment]
进程退出的时候没有及时释放端口，造成了退出之后要隔个一分钟才能再次运行。是个小bug，后面将修复

**Comment by Chion82** [comment]
已修复 https://github.com/Chion82/kcptun-raw/commit/f0ec9b46ff5f08a9df56b3b6fc54840aed20a8cd

**Comment by sdysj** [comment]
Nice, 性能提升很高，原来跑CPU100%，现在40%以下。
